[package]
name = "chess_engine"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dev"
path = "./src/examples/dev.rs"

[dependencies]
chess_game = {path = "../chess_game/"}
itertools = "0.10.5"
tinyvec = "1.6.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "evaluate"
harness = false
